name: simple-mern-app

services:
  mongo:
    image: mongo:7.0.12
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - mern-network

  frontend:
    build:
      context: ./frontend/simple-mern-frontend
      dockerfile: Dockerfile
    container_name: frontend
    depends_on:
      - api
    restart: unless-stopped
    volumes:
      - ./frontend/simple-mern-frontend:/app
      - /app/node_modules
    ports:
      - '5173:5173'
    networks:
      - mern-network

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    ports:
      - '3000:3000'
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongo
    networks:
      - mern-network

volumes:
  mongo-data:
networks:
  mern-network:
    driver: bridge
