name: simple-mern-app-production

services:
  mongo:
    image: mongo:7.0.12
    container_name: simple-mern-app-production-mongo
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongo-data:/data/db
    networks:
      - mern-network

  api:
    build:
      context: ./backend
      dockerfile: dockerfile.prod
    container_name: simple-mern-app-production-backend
    restart: unless-stopped
    ports:
      - '3000:3000'
    env_file:
      - ./backend/.env.production
    networks:
      - mern-network
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend/simple-mern-frontend
      dockerfile: dockerfile.prod
    container_name: simple-mern-app-production-frontend
    restart: unless-stopped
    ports:
      - '80:80'
    env_file:
      - ./frontend/simple-mern-frontend/.env.production
    networks:
      - mern-network
    depends_on:
      - api

volumes:
  mongo-data:

networks:
  mern-network:
    driver: bridge
