# Use the official Node.js image
FROM node:23-slim

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install && apt-get update && apt-get install -y libcurl4

# Copy the rest of the application
COPY . .

# Command to run the app
CMD ["npm", "run", "test"]
